[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dsapp"
version = "0.1.0"
description = "Simple Data Science project"
requires-python = ">=3.10"

dependencies = [
  "pandas>=2.0.0",
  "pytest>=7.0.0"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
