FROM apache/spark:4.2.0-python3

USER root

WORKDIR /app

RUN mkdir -p /app/reports

# PostgreSQL JDBC driver
ADD https://repo1.maven.org/maven2/org/postgresql/postgresql/42.7.13/postgresql-42.7.13.jar \
    /opt/spark/jars/postgresql-42.7.13.jar

# Project files
COPY pyproject.toml .
COPY src ./src

# Install Python dependencies
RUN python3 -m pip install --upgrade pip setuptools wheel && \
    python3 -m pip install --no-cache-dir .

ENV PYTHONPATH=/app/src

RUN chown -R 185:0 /app && \
    chown 185:0 /opt/spark/jars/postgresql-42.7.13.jar

USER 185

CMD ["/opt/spark/bin/spark-submit", \
     "--master", "local[*]", \
     "--conf", "spark.ui.port=4040", \
     "/app/src/utils/spark_pg.py"]