CREATE OR REPLACE DATABASE BMW_DW;

CREATE OR REPLACE SCHEMA BMW_DW.RAW;

CREATE OR REPLACE SCHEMA BMW_DW.STAGING;

CREATE OR REPLACE SCHEMA BMW_DW.ANALYTICS;

CREATE OR REPLACE WAREHOUSE BMW_WH
WITH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;