USE DATABASE BMW_DW;

CREATE OR REPLACE TABLE RAW.RAW_TELEMETRY (
    VEHICLE_ID VARCHAR,
    MODEL VARCHAR,
    BATTERY_LEVEL FLOAT,
    TEMPERATURE FLOAT,
    SPEED FLOAT,
    REGION VARCHAR,
    EVENT_TIMESTAMP TIMESTAMP
);

CREATE OR REPLACE TABLE RAW.RAW_SALES (
    SALES_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    VEHICLE_ID VARCHAR,
    DEALER_ID VARCHAR,
    PURCHASE_DATE DATE,
    SALE_PRICE NUMBER(12,2),
    QUANTITY INTEGER
);

CREATE OR REPLACE TABLE RAW.RAW_VEHICLE (
    VEHICLE_ID VARCHAR,
    MODEL VARCHAR,
    MAKE VARCHAR,
    FUEL_TYPE VARCHAR,
    VEHICLE_YEAR INTEGER,
    SEGMENT VARCHAR
);

CREATE OR REPLACE TABLE RAW.RAW_DEALER (
    DEALER_ID VARCHAR,
    DEALER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    REGION VARCHAR
);