USE DATABASE BMW_DW;

CREATE OR REPLACE TABLE ANALYTICS.DIM_VEHICLE (
    VEHICLE_KEY INTEGER AUTOINCREMENT,
    VEHICLE_ID VARCHAR,
    MODEL VARCHAR,
    MAKE VARCHAR,
    FUEL_TYPE VARCHAR,
    VEHICLE_YEAR INTEGER,
    SEGMENT VARCHAR,
    EFFECTIVE_FROM TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_TO TIMESTAMP,
    IS_CURRENT BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE ANALYTICS.DIM_DEALER (
    DEALER_KEY INTEGER AUTOINCREMENT,
    DEALER_ID VARCHAR,
    DEALER_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    REGION VARCHAR
);

CREATE OR REPLACE TABLE ANALYTICS.DIM_REGION (
    REGION_KEY INTEGER AUTOINCREMENT,
    REGION_NAME VARCHAR,
    COUNTRY VARCHAR,
    ZONE VARCHAR
);

CREATE OR REPLACE TABLE ANALYTICS.DIM_DATE (
    DATE_KEY INTEGER,
    FULL_DATE DATE,
    DAY INTEGER,
    MONTH INTEGER,
    MONTH_NAME VARCHAR,
    QUARTER INTEGER,
    YEAR INTEGER,
    DAY_OF_WEEK INTEGER
);