USE DATABASE BMW_DW;

CREATE OR REPLACE TABLE ANALYTICS.FACT_TELEMETRY (
    TELEMETRY_KEY INTEGER AUTOINCREMENT,
    VEHICLE_KEY INTEGER,
    DATE_KEY INTEGER,
    REGION_KEY INTEGER,
    EVENT_TIMESTAMP TIMESTAMP,
    BATTERY_LEVEL FLOAT,
    TEMPERATURE FLOAT,
    SPEED FLOAT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE ANALYTICS.FACT_SALES (
    SALES_KEY INTEGER AUTOINCREMENT,
    SALES_ID VARCHAR,
    VEHICLE_KEY INTEGER,
    DEALER_KEY INTEGER,
    DATE_KEY INTEGER,
    REGION_KEY INTEGER,
    CUSTOMER_ID VARCHAR,
    SALE_PRICE NUMBER(12,2),
    QUANTITY INTEGER,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);