USE DATABASE BMW_DW;

CREATE OR REPLACE STREAM STAGING.TELEMETRY_STREAM
ON TABLE STAGING.STG_TELEMETRY;

CREATE OR REPLACE STREAM STAGING.SALES_STREAM
ON TABLE STAGING.STG_SALES;

CREATE OR REPLACE STREAM STAGING.VEHICLE_STREAM
ON TABLE STAGING.STG_VEHICLE;

CREATE OR REPLACE STREAM STAGING.DEALER_STREAM
ON TABLE STAGING.STG_DEALER;