CREATE OR REPLACE PROCEDURE STAGING.PROCESS_SALES()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    processed_count INTEGER DEFAULT 0;
BEGIN

    INSERT INTO ANALYTICS.FACT_SALES
    (
        SALES_ID,
        VEHICLE_KEY,
        DEALER_KEY,
        DATE_KEY,
        REGION_KEY,
        CUSTOMER_ID,
        SALE_PRICE,
        QUANTITY
    )
    SELECT
        S.SALES_ID,
        V.VEHICLE_KEY,
        D.DEALER_KEY,
        DT.DATE_KEY,
        R.REGION_KEY,
        S.CUSTOMER_ID,
        S.SALE_PRICE,
        S.QUANTITY
    FROM STAGING.SALES_STREAM S
    JOIN ANALYTICS.DIM_VEHICLE V
        ON S.VEHICLE_ID = V.VEHICLE_ID
       AND V.IS_CURRENT = TRUE
    JOIN ANALYTICS.DIM_DEALER D
        ON S.DEALER_ID = D.DEALER_ID
    JOIN ANALYTICS.DIM_DATE DT
        ON S.PURCHASE_DATE = DT.FULL_DATE
    JOIN ANALYTICS.DIM_REGION R
        ON UPPER(D.REGION) = UPPER(R.REGION_NAME)
    WHERE NOT EXISTS (
        SELECT 1
        FROM ANALYTICS.FACT_SALES F
        WHERE F.SALES_ID = S.SALES_ID
    );

    processed_count := SQLROWCOUNT;

    RETURN 'Sales records processed: ' || processed_count;

END;
$$;