USE DATABASE BMW_DW;

CREATE OR REPLACE PROCEDURE STAGING.PROCESS_TELEMETRY()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    processed_count INTEGER DEFAULT 0;
BEGIN

    INSERT INTO ANALYTICS.FACT_TELEMETRY
    (
        VEHICLE_KEY,
        DATE_KEY,
        REGION_KEY,
        EVENT_TIMESTAMP,
        BATTERY_LEVEL,
        TEMPERATURE,
        SPEED
    )
    SELECT
        V.VEHICLE_KEY,
        D.DATE_KEY,
        R.REGION_KEY,
        S.EVENT_TIMESTAMP,
        S.BATTERY_LEVEL,
        S.TEMPERATURE,
        S.SPEED
    FROM STAGING.TELEMETRY_STREAM S
    JOIN ANALYTICS.DIM_VEHICLE V
        ON S.VEHICLE_ID = V.VEHICLE_ID
       AND V.IS_CURRENT = TRUE
    JOIN ANALYTICS.DIM_DATE D
        ON CAST(S.EVENT_TIMESTAMP AS DATE) = D.FULL_DATE
    JOIN ANALYTICS.DIM_REGION R
        ON UPPER(TRIM(S.REGION)) = UPPER(TRIM(R.REGION_NAME))
    WHERE NOT EXISTS (
        SELECT 1
        FROM ANALYTICS.FACT_TELEMETRY F
        WHERE F.VEHICLE_KEY = V.VEHICLE_KEY
          AND F.EVENT_TIMESTAMP = S.EVENT_TIMESTAMP
    );

    processed_count := SQLROWCOUNT;

    RETURN 'Telemetry records processed: ' || processed_count;

END;
$$;