USE DATABASE BMW_DW;

CREATE OR REPLACE TASK STAGING.TELEMETRY_PROCESS_TASK
WAREHOUSE = BMW_WH
SCHEDULE = '5 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA(
    'BMW_DW.STAGING.TELEMETRY_STREAM'
)
AS
CALL STAGING.PROCESS_TELEMETRY();

--sales
CREATE OR REPLACE TASK STAGING.SALES_PROCESS_TASK
WAREHOUSE = BMW_WH
SCHEDULE = '5 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA(
    'BMW_DW.STAGING.SALES_STREAM'
)
AS
CALL STAGING.PROCESS_SALES();

ALTER TASK STAGING.TELEMETRY_PROCESS_TASK RESUME;

ALTER TASK STAGING.SALES_PROCESS_TASK RESUME;