USE DATABASE BMW_DW;

INSERT INTO ANALYTICS.DIM_VEHICLE
(
    VEHICLE_ID,
    MODEL,
    MAKE,
    FUEL_TYPE,
    VEHICLE_YEAR,
    SEGMENT
)
SELECT
    VEHICLE_ID,
    MODEL,
    MAKE,
    FUEL_TYPE,
    VEHICLE_YEAR,
    SEGMENT
FROM STAGING.STG_VEHICLE;

--dealer
INSERT INTO ANALYTICS.DIM_DEALER
(
    DEALER_ID,
    DEALER_NAME,
    CITY,
    STATE,
    COUNTRY,
    REGION
)
SELECT
    DEALER_ID,
    DEALER_NAME,
    CITY,
    STATE,
    COUNTRY,
    REGION
FROM STAGING.STG_DEALER;

--region
INSERT INTO ANALYTICS.DIM_DEALER
(
    DEALER_ID,
    DEALER_NAME,
    CITY,
    STATE,
    COUNTRY,
    REGION
)
SELECT
    DEALER_ID,
    DEALER_NAME,
    CITY,
    STATE,
    COUNTRY,
    REGION
FROM STAGING.STG_DEALER;

--date dimension
INSERT INTO ANALYTICS.DIM_DATE
SELECT
    TO_NUMBER(TO_CHAR(DATE_VALUE, 'YYYYMMDD')) AS DATE_KEY,
    DATE_VALUE AS FULL_DATE,
    DAY(DATE_VALUE) AS DAY,
    MONTH(DATE_VALUE) AS MONTH,
    MONTHNAME(DATE_VALUE) AS MONTH_NAME,
    QUARTER(DATE_VALUE) AS QUARTER,
    YEAR(DATE_VALUE) AS YEAR,
    DAYOFWEEK(DATE_VALUE) AS DAY_OF_WEEK
FROM (
    SELECT DATEADD(
        DAY,
        SEQ4(),
        '2026-01-01'::DATE
    ) AS DATE_VALUE
    FROM TABLE(GENERATOR(ROWCOUNT => 365))
);