SELECT CURRENT_TIMESTAMP();
SELECT COUNT(*)
FROM ANALYTICS.FACT_TELEMETRY;

DELETE FROM ANALYTICS.FACT_TELEMETRY
WHERE BATTERY_LEVEL < 20;

SELECT *
FROM ANALYTICS.FACT_TELEMETRY
AT (
    OFFSET => -60 * 5
);