CREATE OR REPLACE TABLE ANALYTICS.FACT_TELEMETRY_DEV
CLONE ANALYTICS.FACT_TELEMETRY;

SELECT COUNT(*)
FROM ANALYTICS.FACT_TELEMETRY_DEV;

DELETE FROM ANALYTICS.FACT_TELEMETRY_DEV
WHERE BATTERY_LEVEL < 30;

SELECT COUNT(*)
FROM ANALYTICS.FACT_TELEMETRY;

SELECT COUNT(*)
FROM ANALYTICS.FACT_TELEMETRY_DEV;