--vehicles with low battery
SELECT
    V.MODEL,
    R.REGION_NAME,
    AVG(F.BATTERY_LEVEL) AS AVG_BATTERY_LEVEL
FROM ANALYTICS.FACT_TELEMETRY F
JOIN ANALYTICS.DIM_VEHICLE V
    ON F.VEHICLE_KEY = V.VEHICLE_KEY
JOIN ANALYTICS.DIM_REGION R
    ON F.REGION_KEY = R.REGION_KEY
GROUP BY
    V.MODEL,
    R.REGION_NAME
ORDER BY AVG_BATTERY_LEVEL;

--average temperature
SELECT
    V.MODEL,
    AVG(F.TEMPERATURE) AS AVG_TEMPERATURE
FROM ANALYTICS.FACT_TELEMETRY F
JOIN ANALYTICS.DIM_VEHICLE V
    ON F.VEHICLE_KEY = V.VEHICLE_KEY
GROUP BY V.MODEL
ORDER BY AVG_TEMPERATURE DESC;

--sales revenue
SELECT
    V.MODEL,
    SUM(F.SALE_PRICE * F.QUANTITY) AS TOTAL_REVENUE,
    SUM(F.QUANTITY) AS UNITS_SOLD
FROM ANALYTICS.FACT_SALES F
JOIN ANALYTICS.DIM_VEHICLE V
    ON F.VEHICLE_KEY = V.VEHICLE_KEY
GROUP BY V.MODEL
ORDER BY TOTAL_REVENUE DESC;    

--regional sales
SELECT
    R.REGION_NAME,
    SUM(F.SALE_PRICE * F.QUANTITY) AS REVENUE
FROM ANALYTICS.FACT_SALES F
JOIN ANALYTICS.DIM_REGION R
    ON F.REGION_KEY = R.REGION_KEY
GROUP BY R.REGION_NAME
ORDER BY REVENUE DESC;

--critical vehicles
SELECT
    V.VEHICLE_ID,
    V.MODEL,
    R.REGION_NAME,
    F.BATTERY_LEVEL,
    F.TEMPERATURE,
    F.EVENT_TIMESTAMP
FROM ANALYTICS.FACT_TELEMETRY F
JOIN ANALYTICS.DIM_VEHICLE V
    ON F.VEHICLE_KEY = V.VEHICLE_KEY
JOIN ANALYTICS.DIM_REGION R
    ON F.REGION_KEY = R.REGION_KEY
WHERE F.BATTERY_LEVEL < 20
ORDER BY F.BATTERY_LEVEL;