[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Kafkaproducer"
version = "0.1.0"
description = "A Kafka producer application"
requires-python = ">=3.10"
dependencies = [
    "pandas",
    "httpx",
    "fastapi",
    "uvicorn[standard]",    
    "python-dotenv",
    "confluent-kafka",
    "fastapi",
    "langchain-aws",
    "langchain-core",
    "requests"
]

[project.optional-dependencies]
dev = ["pytest>=8,<9", "ruff>=0.9,<1"]

[tool.hatch.build.targets.wheel]
packages = ["src/kafkaapp"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 100
target-version = "py310"
