"""Local query layer for the FastAPI application.

During local development the API reads curated CSV files generated by the
pipeline. In the AWS deployment this layer can be replaced by an Athena
query implementation without changing the API route contract.
"""

from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT/"data/curated_local"

def read(name):
    """Read one curated CSV dataset from the local analytics directory."""
    return pd.read_csv(DATA/name)

def summary():
    """Return dashboard-level summary metrics."""
    v = read("vehicle_efficiency.csv")
    return {
        "total_vehicles": int(v.vehicle_id.nunique()),
        "avg_efficiency": float(v.overall_efficiency.mean()),
        "avg_range": float(v.avg_estimated_range_km.mean()),
        "total_distance": float(v.total_distance_km.sum())
    }

def top_vehicles(limit=5):
    """Return the highest-efficiency vehicles as API records."""
    return read("vehicle_efficiency.csv").nlargest(
        limit, "overall_efficiency"
    ).to_dict("records")

def bottom_vehicles(limit=5):
    """Return the lowest-efficiency vehicles as API records."""
    return read("vehicle_efficiency.csv").nsmallest(
        limit, "overall_efficiency"
    ).to_dict("records")

def models():
    """Return model-level efficiency records."""
    return read("model_efficiency.csv").to_dict("records")

def regions():
    """Return region-level efficiency records."""
    return read("region_efficiency.csv").to_dict("records")

def range_trend():
    """Return daily estimated-range trend records."""
    return read("range_trend.csv").to_dict("records")
